### ISSUE TITLE
Bug when using dir argument to mcmcplot

### ISSUE THREAD

**Issue by nylander** [s-mckay-curtis/mcmcplots#10]
Hi,
I'm confused by the `dir` argument to `mcmcplot` - isn't it supposed to create a directory if it's not present? I need to create the folder first, otherwise `mcmcplot` fails with message:

`>  mcmcplot(mcmcdat, dir = "apa")
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'apa/MCMCoutput.html': No such file or directory`

/johan

**Comment by s-mckay-curtis** [comment]
As it is currently implemented, the directory in the dir argument must exist. It's an interesting suggestion however to have the mcmcplot function create the directory if it does not exist. I am somewhat undecided on this issue though. In the interest of avoiding side effects, I can see the benefits of not having the function create the directory for you. At the very least, I should be more explicit in the docs and I should probably have the function error out more elegantly if the directory does not exist.

**Comment by s-mckay-curtis** [comment]
Changed the docs and added a more informative error.
